### ISSUE TITLE
Syntax error line 5

### ISSUE THREAD

**Issue by esturniolo** [google/import-mailbox-to-gmail#24]
Hi.
There is no log. The stdout shows the following (Debian Jessie)

```
eas@debianMaster:~$ ./import-mailbox-to-gmail.py --json /home/eas/TJemail-842823h79543.json --dir /home/eas/mbox/
./import-mailbox-to-gmail.py: línea 5: error sintáctico cerca del elemento inesperado `newline'
./import-mailbox-to-gmail.py: línea 5: `<!DOCTYPE html>'
```

In english:

```
./import-mailbox-to-gmail.py: line 5: syntax error unexpected element 'newline'
./import-mailbox-to-gmail.py: line 5: `<!DOCTYPE html>'
```

Any ideas?

thanks!

**Comment by PMox** [comment]
I think that instead of performing a GIT checkout or downloading the RAW data, you downloaded the HTML page, which has the doctype exactly at line 5:

![screen shot 2017-02-12 at 20 22 47](https://cloud.githubusercontent.com/assets/929976/22865293/22dab012-f161-11e6-922c-e219abc58392.png)

Can you please try to download the RAW version instead:
https://raw.githubusercontent.com/google/import-mailbox-to-gmail/master/import-mailbox-to-gmail.py

**Comment by esturniolo** [comment]
You're wright. My bad.
I ran the script again with the RAW version and MAGIC.

I'll cry.

Thanks for your effort PMox. It works like a charm!
